version: '3.9'

services:
  frontend: 
    build:
      context: frontend
    image: counter_frontend
    ports:
      - 3100:3100
      - 3000:3000
    environment:
      REACT_APP_CAPTCHA_SITE_KEY: ${CAPTCHA_SITE_KEY}
      REACT_APP_BACKEND_URL: ${BACKEND_URL:-http://localhost:8080}

  backend: 
    image: diegosteinerzli/counter_kand_backend
    build:
      context: backend
    ports:
      - 8080:8080
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_NAME: counter
      DB_USER: postgres
      DB_PASSWORD: password
      PASSPHRASE: secret
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: counter

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8083:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
